# Generated by Django 5.1.2 on 2024-10-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('main_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Основной номер телефона')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='AdditionalPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Доп. номер телефона')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'доп. номер телефона',
                'verbose_name_plural': 'Доп. номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Доп. email')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'email',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='social_icons/', verbose_name='Иконка соц. сети')),
                ('url', models.URLField(verbose_name='Ссылка на соц. сеть')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='settings.sitesettings')),
            ],
            options={
                'verbose_name': 'соц.сеть',
                'verbose_name_plural': 'соц.сети',
            },
        ),
    ]
