# Generated by Django 5.1.2 on 2024-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(help_text='Укажите код карты получателя', verbose_name='Номер карты')),
                ('bank', models.CharField(help_text='Укажите название банка получателя', max_length=255, verbose_name='Название банка')),
                ('owner', models.CharField(help_text='Укажите ФИО получателя', max_length=255, verbose_name='Получатель')),
                ('is_accent', models.BooleanField(default=False, verbose_name='Отображать на главной странице')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
