# Generated by Django 5.1.2 on 2024-10-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': 'Реквизит', 'verbose_name_plural': 'Список реквизитов'},
        ),
    ]
